# Generated by Django 4.0.3 on 2022-03-31 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=35)),
                ('email', models.CharField(max_length=35)),
                ('telefone', models.CharField(max_length=12)),
                ('endereço_completo', models.CharField(max_length=35)),
                ('profissão', models.CharField(max_length=35)),
                ('curriculo_upload', models.FileField(blank=True, upload_to='curriculos/%d/%m/%Y/')),
            ],
        ),
    ]
