# Generated by Django 4.0.3 on 2022-03-31 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='profissão',
            new_name='profissao',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereço_completo',
            field=models.CharField(max_length=200),
        ),
    ]
